kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-grp1-admin-binding
  namespace: grp1-common
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:roleRef': {}
        'f:subjects': {}
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: grp1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
