apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-partial-access
  namespace: grp1-common
rules:
- apiGroups: [""]
  resources: [" pods secrets services configs routes buildconfigs daemonsets deployments replicasets statefulsets builds imagestreams "]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-rolebinding
  namespace: grp1-common
subjects:
- kind: Group
  name: grp1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ns-partial-access
  apiGroup: rbac.authorization.k8s.io
