apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-partial-access
  namespace: grp2-common
rules:
- apiGroups: [""]
  resources: [" pods pods/attach pods/exec pods/portforward pods/proxy groupsyncs.redhatcop.redhat.io erviceaccounts projects projects.project.openshift.io namespaces namespaces/status services roles clusterroles clusterroles.rbac.authorization.k8s.io clusterroles.authorization.openshift.io users users.user.openshift.io projects.project.openshift.io routes templates roles secrets services configs routes buildconfigs daemonsets deployments replicasets statefulsets builds imagestreams endpoints "]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-rolebinding
  namespace: grp2-common
subjects:
- kind: Group
  name: grp2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ns-partial-access
  apiGroup: rbac.authorization.k8s.io
