apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: grp1-common
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: "900Mi"
          cpu: "500m"
