apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-partial-access
  namespace: grp1-common
rules:
- apiGroups: [""]
  resources: ["pods secrets services configs routes buildconfigs daemonsets deployments replicasets statefulsets builds imagestreams"]
  verbs: ["*"]
