apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-partial-access
  namespace: grp2-common
rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    - projects
    - resourcequotas
    verbs:
    - get
    - list
  - apiGroups:
    - ""
    resources:
    - configmaps
    - pods
    - secrets
    - endpoints
    - deployments
    - deploymentconfigs
    - replicasets
    - replicationcontrollers
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
    - create
  - apiGroups:
    - "apps"
    resources:
    - configmaps
    - pods
    - secrets
    - endpoints
    - deployments
    - deploymentconfigs
    - replicasets
    - replicationcontrollers
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
    - create
  - apiGroups:
    - "image.openshift.io"
    resources:
    - imagestreams
    verbs:
    - get
    - list
    - create
  - apiGroups:
    - "build.openshift.io"
    resources:
    - builds
    - buildconfigs
    verbs:
    - get
    - list
    - create
  - apiGroups:
    - "tekton.dev"
    resources:
    - tasks
    - pipelines
    - pipelineruns
    - taskruns
    - pipelineresources
    verbs:
    - get
    - watch
    - list
    - create
    - delete
  - apiGroups:
    - "pipelinesascode.tekton.dev"
    resources:
    - repositories
    verbs:
    - get
    - watch
    - list
    - create
  - apiGroups:
    - "triggers.tekton.dev"
    resources:
    - eventlisteners
    - triggertemplates
    - triggerbindings
    verbs:
    - get
    - watch
    - list
    - create
  - apiGroups:
    - project.openshift.io
    resources:
    - projects
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - "apps.openshift.io" 
    resources:
    - deploymentconfigs
    verbs:
    - get
    - list
    - watch
    - create
  - apiGroups:
    - "route.openshift.io"
    resources:
    - routes
    verbs:
    - get
    - list
    - watch
    - create
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    - networking.k8s.io
    resources:
    - ingresses
    - networkpolicies
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    - networking.k8s.io
    resources:
    - ingresses/status
    verbs:
    - update
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingressclasses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - ingress-controller-leader-nginx
    resources:
    - configmaps
    verbs:
    - get
    - update
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - event
    verbs:
    - create
    - patch
  - apiGroups:
    - "events.k8s.io"
    resources:
    - event
    verbs:
    - create
    - list
    - watch
    - get
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-rolebinding
  namespace: grp2-common
subjects:
- kind: Group
  name: grp2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ns-partial-access
  apiGroup: rbac.authorization.k8s.io
