apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-rolebinding
  namespace: devsecops-simple-demo
subjects:
- kind: Group
  name: devsecops-simple-demo
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ns-partial-access
  apiGroup: rbac.authorization.k8s.io
