apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-partial-access
  namespace: grp1-common
rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - configmaps
    - pods
    - secrets
    - endpoints
    - deployments
    - deploymentconfigs
    - replicasets
    - replicationcontrollers
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
    - create
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    - networking.k8s.io
    resources:
    - ingresses/status
    verbs:
    - update
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingressclasses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - ingress-controller-leader-nginx
    resources:
    - configmaps
    verbs:
    - get
    - update
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-rolebinding
  namespace: grp1-common
subjects:
- kind: Group
  name: grp1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ns-partial-access
  apiGroup: rbac.authorization.k8s.io
